/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
  java
  id("com.github.ben-manes.versions") version "0.27.0"
}

repositories {
  jcenter()
}

dependencies {
  implementation("com.google.inject:guice:3.0")
}
